app:
  db_url: postgresql://neondb_owner:npg_BQtXAv7wi1VD@ep-purple-snow-asqpnm5n-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  poll_interval_seconds: 900
  request_timeout_seconds: 20
  min_delay_between_requests_seconds: 2
  max_delay_between_requests_seconds: 7

notifications:
  console:
    enabled: true

  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""

  sms:
    enabled: false
    provider: "kavenegar"
    api_key: ""
    sender: ""
    receptor: ""
    
  bale:
    enabled: true
    bot_token: "1579117131:sQZas-un8MsqRcxphWR4sgWRSGkqL_K1Png"
    chat_id: "1920666644"

web:
  host: "127.0.0.1"
  port: 8000
  

defaults:
  conditions:
    notify_when_available: true
    notify_when_unavailable: true
    max_price_toman: null
    min_discount_percent: null
    only_digikala_seller: false
    seller_names_include: []
    seller_names_exclude: []
    notify_on_any_price_change: false
    notify_on_price_drop_percent: null
    notify_on_seller_change: true
    notify_on_new_seller: true
    notify_on_removed_seller: true
    notify_on_discount_change: true
    min_stock_count: null
    allowed_warranties: []
    blocked_warranties: []
